resolver: lts-6.2
ghc-options:
    werewolf-slack: -Werror -Wall -fno-warn-name-shadowing

packages:
- '.'
extra-deps:
- url: https://github.com/xcloudx12345/werewolf/archive/refs/tags/v1.4.0.1.tar.gz
